version: '3.6'

volumes:
  pbft-shared:

services:
  shell-0:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-0
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-1:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-1
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-2:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-2
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-3:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-3
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-4:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-4
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-5:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-5
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-6:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-6
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-7:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-7
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-8:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-8
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-9:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-9
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-10:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-10
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-11:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-11
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-12:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-12
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-13:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-9
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-14:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-14
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  shell-15:
    image: hyperledger/sawtooth-shell:chime
    container_name: sawtooth-shell-default-15
    volumes:
      - pbft-shared:/pbft-shared
      - ./scripts:/scripts
      - ./binary:/binary
    command: |
      bash -c "
        sawtooth keygen
        tail -f /dev/null
      "
    stop_signal: SIGKILL

  rest-api-0:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default-0
    expose:
      - 8008
    ports:
      - "8008:8008"
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-0:4004 \
          --bind rest-api-0:8008
      "
    stop_signal: SIGKILL

  rest-api-1:
    image: hyperledger/sawtooth-rest-api:chime
    container_name: sawtooth-rest-api-default-1
    expose:
      - 8008
    command: |
      bash -c "
        sawtooth-rest-api \
          --connect tcp://validator-1:4004 \
          --bind rest-api-1:8008
      "
    stop_signal: SIGKILL

  settings-tp-0:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default-0
    expose:
      - 4004
    command: settings-tp -C tcp://validator-0:4004
    stop_signal: SIGKILL

  settings-tp-1:
    image: hyperledger/sawtooth-settings-tp:chime
    container_name: sawtooth-settings-tp-default-1
    expose:
      - 4004
    command: settings-tp -C tcp://validator-1:4004
    stop_signal: SIGKILL

  validator-0:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-0
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-0.priv ]; then
          cp /pbft-shared/validators/validator-0.pub /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator-0.priv /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /pbft-shared/validators/validator-0.pub
          cp /etc/sawtooth/keys/validator.priv /pbft-shared/validators/validator-0.priv
        fi &&
        if [ ! -e config-genesis.batch ]; then
          sawset genesis -k /etc/sawtooth/keys/validator.priv -o config-genesis.batch
        fi &&
        while [[ ! -f /pbft-shared/validators/validator-1.pub ]];
        do sleep 1; done
        echo sawtooth.consensus.pbft.members=\\['\"'$$(cat /pbft-shared/validators/validator-0.pub)'\"','\"'$$(cat /pbft-shared/validators/validator-1.pub)'\"'\\] &&
        if [ ! -e config.batch ]; then
         sawset proposal create \
            -k /etc/sawtooth/keys/validator.priv \
            sawtooth.consensus.algorithm.name=pbft \
            sawtooth.consensus.algorithm.version=1.0 \
            sawtooth.consensus.pbft.members=\\['\"'$$(cat /pbft-shared/validators/validator-0.pub)'\"','\"'$$(cat /pbft-shared/validators/validator-1.pub)'\"'\\] \
            sawtooth.publisher.max_batches_per_block=1000 \
            -o config.batch
        fi &&
        if [ ! -e /var/lib/sawtooth/genesis.batch ]; then
          sawadm genesis config-genesis.batch config.batch
        fi &&
        if [ ! -e /root/.sawtooth/keys/my_key.priv ]; then
          sawtooth keygen my_key
        fi &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-0:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000
      "

  validator-1:
    image: hyperledger/sawtooth-validator:chime
    container_name: sawtooth-validator-default-1
    expose:
      - 4004
      - 5050
      - 8800
    volumes:
      - pbft-shared:/pbft-shared
    command: |
      bash -c "
        if [ -e /pbft-shared/validators/validator-1.priv ]; then
          cp /pbft-shared/validators/validator-1.pub /etc/sawtooth/keys/validator.pub
          cp /pbft-shared/validators/validator-1.priv /etc/sawtooth/keys/validator.priv
        fi &&
        if [ ! -e /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen
          mkdir -p /pbft-shared/validators || true
          cp /etc/sawtooth/keys/validator.pub /pbft-shared/validators/validator-1.pub
          cp /etc/sawtooth/keys/validator.priv /pbft-shared/validators/validator-1.priv
        fi &&
        sawtooth keygen my_key &&
        sawtooth-validator -vv \
          --endpoint tcp://validator-1:8800 \
          --bind component:tcp://eth0:4004 \
          --bind consensus:tcp://eth0:5050 \
          --bind network:tcp://eth0:8800 \
          --scheduler parallel \
          --peering static \
          --maximum-peer-connectivity 10000 \
          --peers tcp://validator-0:8800
      "

  pbft-0:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-default-0
    command: pbft-engine -vv --connect tcp://validator-0:5050
    stop_signal: SIGKILL

  pbft-1:
    image: hyperledger/sawtooth-pbft-engine:chime
    container_name: sawtooth-pbft-engine-default-1
    command: pbft-engine -vv --connect tcp://validator-1:5050
    stop_signal: SIGKILL

  autavail-tp-0:
    image: guilhermeeec/sawtooth-autavail-tp-go:3
    container_name: sawtooth-autavail-tp-go-0
    expose:
      - 4004
    volumes:
      - ./binary:/binary
    command: autavail-tp-go -vv -C tcp://validator-0:4004 --max-queue-size 3200
    stop_signal: SIGKILL

  autavail-tp-1:
    image: guilhermeeec/sawtooth-autavail-tp-go:3
    container_name: sawtooth-autavail-tp-go-1
    expose:
      - 4004
    volumes:
      - ./binary:/binary
    command: autavail-tp-go -vv -C tcp://validator-1:4004 --max-queue-size 3200
    stop_signal: SIGKILL
